//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportPDF2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal Monthly_water_bill { get; set; }
        public System.DateTime Date_of_readings { get; set; }
        public System.DateTime Pay_at_the_branch_up_to { get; set; }
        public System.DateTime Pay_agent_no_more_than { get; set; }
    }
}
